services:
  # node:
  #   image: "node:latest"
  #   user: "node"
  #   working_dir: /home/node/app
  #   environment:
  #     - NODE_ENV=development
  #   volumes:
  #     - ./:/home/node/app
  #   ports: # use if it is necessary to expose the container to the host machine
  #     - "3000:3000"
  #   command: ["npm", "start"]
  mongo:
    image: mongo:7
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mydb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass
volumes:
  mongo-data: {}